name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Change this if your default branch is different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Clean project
        run: |
          if [ -d "dist" ]; then
            rm -rf dist
          fi

      - name: Build your site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          publish_dir: dist